AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Shipping cost calculator lambda function

Resources:
  PriceCalculatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 30
      MemorySize: 128
      Layers:
        - !Ref DependenciesLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /shipping-cost
            Method: post

  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: shipping-price-calculator-dependencies
      Description: Dependencies for shipping-price calculator
      ContentUri: dependencies/
      CompatibleRuntimes:
        - python3.9